baseurl = "https://oliversabler.github.io/"
languageCode = "en-us"
title = "Nest"
theme = "cactus"
paginate = 10
disableKinds = ['taxonomyTerm']
googleAnalytics = "G-2JHWLJYCQH"

[params]
    author = "Oliver Sabler"


[Author]
    name = "Oliver Sabler"

